<?php
	$consumer_key = FreshRSS_Context::$user_conf->pocket_consumer_key;
	$username = FreshRSS_Context::$user_conf->pocket_username;
	$access_token = FreshRSS_Context::$user_conf->pocket_access_token;
	$keyboard_shortcut = FreshRSS_Context::$user_conf->pocket_keyboard_shortcut;
?>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="keyboard_shortcut"><?php echo _t('ext.pocketButton.configure.keyboard_shortcut'); ?></label>
		<div class="group-controls">
			<input type="text" name="keyboard_shortcut" id="keyboard_shortcut" maxlength="1" value="<?php echo $keyboard_shortcut; ?>">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
		</div>
	</div>
</form>

<?php if ($this->isEnabled()): ?>
<form action="<?php echo _url('pocketButton', 'requestAccess'); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="consumer_key"><?php echo _t('ext.pocketButton.configure.consumer_key'); ?></label>
		<div class="group-controls">
			<input type="text" name="consumer_key" id="consumer_key" value="<?php echo $consumer_key; ?>">
		</div>
	</div>

	
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('ext.pocketButton.configure.connect_to_pocket'); ?></button>
		</div>
	</div>
</form>
<?php else: ?>
	<p class="alert alert-warn">
		<?php echo _t('ext.pocketButton.configure.extension_disabled'); ?>
	</p>
<?php endif ?>

<?php if (!empty($username)): ?>
	<p><b><?php echo _t('ext.pocketButton.configure.username'); ?>:</b> <?php echo $username; ?></p>
<?php endif ?>

<?php if (!empty($access_token)): ?>
	<p><b><?php echo _t('ext.pocketButton.configure.access_token'); ?>:</b> <?php echo $access_token; ?></p>
<?php endif ?>
